version: "2"
services: 
    mongo:
        container_name: "mongo"
        restart: "always"
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        volumes:
            - ./mongo_data:/data/db
        ports:
            - "27017:27017"
    # app: 
    #     container_name: "app"
    #     restart: "always"
    #     build: .
    #     ports: 
    #         - "8081:8081"
    #     links: 
    #         - "mongo"
